default_config:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.0.31:3218/ #CHANGE THIS... for url: <hostip> substituted ip address of my Pi on the LAN
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://192.168.0.31:1880/ #CHANGE THIS... for <hostip> substituted ip address of my Pi on the LAN
    require_admin: true
mqtt:
  broker: 192.168.0.31 ##CHANGE THIS... substituted Pi's LAN IP address for <hostip>
  
recorder:
  db_url: !secret ha_db_url #now referring to my secrets file located in this same directory (secrets.yaml after removing .sample suffix)
  #db_url: mysql://homeassistant:<ha_dbdatabasepassword>@<hostip>/ha_db?charset=utf8
  #^How the option was originally configured
  purge_keep_days: 30
