default_config:

panel_iframe:
  configurator:
    title: Configurator  # If you're altering this file because, for whatever reason, you don't want to use the secrets.yaml file
    icon: mdi:wrench # keep the indentation as is, as you revert the following line and make it appear like url: http://192.168.0.31:3218
    url: !secret configurator_url #url: http://<hostip>:3218/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant #likewise, you will need to edit the url line below,
    url: !secret nodered_url  #replacing it with   url: http://<hostip>:1880/
    require_admin: true
    
mqtt:        #Change this as well to your LAN IP address for 
  broker: !secret hostip #broker: <hostip>
  
recorder: #again, this now refers to value of the key "ha_db_url" in my secrets.yaml file located in this same directory
  db_url: !secret ha_db_url  #the original configuration appears below, commented out
  #db_url: mysql://homeassistant:<ha_dbdatabasepassword>@<hostip>/ha_db?charset=utf8
  purge_keep_days: 30
